FROM oven/bun:1

WORKDIR /usr/src/app

ARG DATABASE_URL

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

RUN bun install

RUN bun db:generate

RUN DATABASE_URL=${DATABASE_URL} bun run build

EXPOSE 3000

CMD [ "bun", "run", "start:web" ]

# build command => docker build --build-arg DATABASE_URL=postgresql://postgres:moneymoneymoney@localhost:5432/postgres -t monorepo-frontend -f ./docker/Dockerfile.frontend .