FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/http-backend ./apps/http-backend

RUN bun install

RUN bun db:generate

EXPOSE 8081

CMD [ "bun", "run", "start:ws" ]

# build command => docker build -t monorepo-websocket -f ./docker/Dockerfile.backend .