name: Backend Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push # pushing to docker hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: bhargavshekhar/monorepo-backend:${{ github.sha }}
      - name: Deploy to the VM
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          chmod 700 /home/runner/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@15.207.98.139 -t "docker stop backend || true && docker rm backend || true && docker run -d --name backend -p 8080:8080 bhargavshekhar/monorepo-backend:${{ github.sha }}"
